# 2. Estructura de Datos

Conozca las estructuras de datos de Python: obtenga más información sobre los tipos de datos y las estructuras de datos primitivas y no primitivas, como **string, list**, etc.

Las estructuras de datos son una forma de organizar y almacenar datos para que se pueda acceder a ellos y trabajar de manera eficiente. Definen la relación entre los datos y las operaciones que se pueden realizar con los mismos. Hay muchos tipos de estructuras de datos definidas que permiten concentrarse en la resolución de problemas en lugar de perderse en los detalles de la descripción y el acceso a los datos.

![valores](imagenes/3.ArbolData.png)

Las estructuras de datos se pueden dividir en dos categorías: estructuras de datos primitivas y no primitivas.
Las primeras son las formas más simples de representar datos, mientras que las segundas son más avanzadas: contienen las estructuras de datos primitivas dentro de estructuras de datos más complejas para propósitos especiales.

## 2.1. Estructuras de datos primitivas

Estas son las estructuras de datos más primitivas o básicas. Son los componentes básicos para la manipulación de datos y contienen valores puros y simples de datos. Python tiene cuatro tipos de variables primitivas:


- **Integers**
- **Float**
- **Strings**
- **Boolean**

### Integers
Representa datos numéricos y, más específicamente, **números enteros** desde infinito negativo hasta infinito, como **-4**, **0** o **4**.

### Float
Puede usarlo para números racionales, que generalmente terminan con una **cifra decimal**, como **1,11** o **3,14**.

 *En la siguiente celda se muestran algunas operaciones con números enteros y flotantes!*

In [4]:
# Floats
x = 4.0 
y = 2.1
print(type(x))

#Integer
z = 10
print(type(z))

print(x + y + z)    # Addition
print(x - y)        # Subtraction
print(x * z)      # Multiplication
print(x / y)        # Returns the quotient (cociente)
print(x % y)        # Returns the remainder(resto)
print(abs(x))       # Absolute value
print(x ** z)       # x to the power y

<class 'float'>
<class 'int'>
16.1
1.9
40.0
1.9047619047619047
1.9
4.0
1048576.0


### String
Son colecciones de alfabetos, palabras u otros caracteres. En Python, puede crear cadenas encerrando una secuencia de caracteres entre un par de comillas simples o dobles. Por ejemplo: **'Adrisk', "Actuarios"**, etc.

También puede aplicar las operaciones + en dos o más cadenas para concatenarlas, como en el siguiente ejemplo:

In [8]:
x = 'Actuarios'
y = 'Vida'
x + ' ' + y

'Actuarios Vida'

In [22]:
# Repeat
x * 2

'ActuariosActuarios'

#### También puede dividir cadenas, lo que significa que selecciona partes del string:

In [15]:
palabra = "productos"

In [26]:
abc = palabra[3:]      # elem 0 y elem 1
print(abc)

ductos


In [30]:
# Range Slicing
z1 = x[:6] 

print(z1)

# Slicing
z2 = y[0] + y[1] 

print(z2)


Actuar
Vi


Tenga en cuenta que las cadenas también pueden ser caracteres alfanuméricos, pero que la operación **+** 
también se usa para concatenar strings.

In [31]:
x = '4'
y = '2'

print(x + y)
print(type(x+y))

42
<class 'str'>


In [32]:
x = 4
y = 2

print(x + y)
print(type(x+y))

6
<class 'int'>


Python tiene muchos métodos integrados o funciones auxiliares para manipular strings. Reemplazar una subcadena, poner en mayúscula ciertas palabras en un párrafo, encontrar la posición de una cadena dentro de otra cadena son algunas de las manipulaciones comunes de cadenas. Mira algunos de estos:
- ### mayúsculas

In [33]:
str.capitalize('programa')


'Programa'

- ### len
Recupera la longitud de una cadena en caracteres.  
Tenga en cuenta que los espacios también cuentan para el resultado final:

In [49]:
str1 = "Especialización 1_2"
str2 = " 202102 "
len(str2)
str3 = str2.split()
print(str3)
str3 = str3[0]

['202102']


- Compruebe si una cadena consta solo de dígitos

In [50]:
str3.isdigit() 

True

- Reemplazar partes de un string con otro

In [51]:
str1.replace('1_2', str2)

'Especialización  202102 '

### Boolean
Este tipo de datos incorporado que puede tomar los valores: **Verdadero** y **Falso**, lo que a menudo los hace intercambiables con los enteros 1 y 0. Los booleanos son útiles en expresiones condicionales y de comparación, al igual que en los siguientes ejemplos:

In [54]:
x = 4
y = 7
x == y

False

In [55]:
y > x

True

In [66]:
x = 4
y = 3
z = (x==y) # Comparison expression (Evaluates to false)

if  z == True : # Conditional on truth/false value of 'z'
    print(" x es igual a y")
else: print("son diferentes")
    
print(type(z))    

son diferentes
<class 'bool'>


## 2.1.1. Data Type Conversion
A veces, se encontrará trabajando en el código de otra persona y deberá convertir un número entero en un flotante o viceversa. O tal vez descubra que ha estado usando un número entero cuando lo que realmente necesita es un flotante. En tales casos, puede convertir el tipo de datos de las variables.

Para verificar el tipo de un objeto en Python, use la función incorporada **type()**, como en las líneas de código a continuación:


In [76]:
i = 9.0
i = int(i*2)
type(i)
print(i)

18


Puede haber dos tipos posibles de conversión de datos: **implícita** denominada coerción y **explícita**, a menudo denominada conversión.  
#### Conversión de tipo de datos implícita
Se trata de una **conversión automática** de datos y el compilador se encarga de ello. Eche un vistazo a los siguientes ejemplos:

In [70]:

x = 9.0  # A float
y = 2  # An integer

z = x/y 

# Check the type of `z`
type(z)

float

En el ejemplo anterior, no tenía que cambiar explícitamente el tipo de datos de **y** para realizar la división de valor flotante. El compilador hizo esto implícitamente por usted.

#### Conversión explícita de tipos de datos
Este tipo de conversión de tipo de datos lo define el usuario, lo que significa que debe informar explícitamente al compilador que cambie el tipo de datos de cierto objeto. Considere el fragmento de código a continuación para comprender completamente esto:

In [78]:
x = 202102
y = "Python para actuarios vida : "
texto = y + x

TypeError: can only concatenate str (not "int") to str

El ejemplo anterior le dio un error porque el compilador no entiende que está intentando realizar una concatenación o una suma, debido a los tipos de datos mixtos. Tienes un número entero y una cadena que estás intentando sumar.  
Hay un desajuste obvio.
Para resolver esto, primero **deberá convertir el int en un string** para luego poder realizar la concatenación.

In [81]:
x = 202102
y = "Python para actuarios vida : "
texto = y + str(x)
print(texto)

Python para actuarios vida : 202102


## 2.2. Estructuras de datos no primitivas

Los tipos no primitivos son los miembros sofisticados de la familia de estructuras de datos. No solo almacenan un valor, sino una colección de valores en varios formatos.

Las estructuras de datos no primitivas se dividen en:


- **Array**
- **List**
- **Tuple**
- **Dictionary**
- **File**

### Array
En Python, las matrices son compatibles con el ** módulo  array** y deben **importarse** antes de comenzar a iniciarlas y usarlas. Los elementos almacenados en una matriz están restringidos en su tipo de datos. El tipo de datos se especifica durante la creación de la matriz y se especifica mediante un código de tipo, que es un carácter único como el que ve en el ejemplo siguiente:

In [82]:
import array as arr
a = arr.array("I",[3,6,9])
print(type(a))
print(a)

<class 'array.array'>
array('I', [3, 6, 9])


Aquí hay un código para comenzar con NumPy Array:

In [84]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3 # Performing vectorized (element-wise) operations 
print(arr_b)


arr_ones = np.ones(4)
print(arr_ones)

multi_arr_ones = np.ones((3,4)) # Creating 2D array with 3 rows and 4 columns
print(multi_arr_ones)


[1. 2. 3.]
[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### List
Las listas se utilizan para almacenar una colección de elementos heterogéneos. Estos son mutables, lo que significa que puede cambiar su contenido sin cambiar su identidad. Puede reconocer las listas por sus corchetes **[x,y,x]** que contienen elementos, separados por una coma,. Las listas están integradas en Python: no es necesario invocarlas por separado.

In [86]:
x = [] # Empty list
print(type(x))

x1 = [1,2,3]
print(type(x1))
type(x1)

x2 = list([1,'apple',3])
print(x2[1])

x2[1] = 'orange'  # cambiamos el segundo elemento
print(x2)


<class 'list'>
<class 'list'>
apple
[1, 'orange', 3]


Python proporciona muchos métodos para manipular y trabajar con listas. Agregar nuevos elementos a una lista, eliminar algunos elementos de una lista, ordenar o invertir una lista son manipulaciones comunes de listas. Veamos algunos de ellos en acción:

In [87]:
list_num = [1,2,45,6,7,2,90,23,435]
list_char = ['c','o','o','k','i','e']

list_num.append(11) # Add 11 to the list, by default adds to the last position
print(list_num)


list_num.insert(0, 12) #  insert 11 at index or position 0 
print(list_num)

list_char.remove('o') 
print(list_char)

re = list_char.pop(-2) # Removes the item at the specified position
print(list_char)
print(re)

list_num.sort() # In-place sorting
print(list_num)

list.reverse(list_num)
print(list_num)

[1, 2, 45, 6, 7, 2, 90, 23, 435, 11]
[12, 1, 2, 45, 6, 7, 2, 90, 23, 435, 11]
['c', 'o', 'k', 'i', 'e']
['c', 'o', 'k', 'e']
i
[1, 2, 2, 6, 7, 11, 12, 23, 45, 90, 435]
[435, 90, 45, 23, 12, 11, 7, 6, 2, 2, 1]


### Tuples
Las tuplas son otro tipo de datos de secuencia estándar. La diferencia entre tuplas y lista es que las tuplas son inmutables, lo que significa que una vez definidas no puede eliminar, agregar o editar ningún valor dentro de ellas. Esto puede ser útil en situaciones en las que podría pasar el control a otra persona pero no desea que manipulen los datos de su colección.

Veamos cómo se implementan las tuplas:

In [88]:
x_tuple = 1,2,3,4,5
y_tuple = ('c','a','k','e')

x_tuple[0]

1

In [89]:
y_tuple[3]
x_tuple[0] = 0 # Cannot change values inside a tuple

TypeError: 'tuple' object does not support item assignment

### Dictionary

Los diccionarios son exactamente lo que necesita si desea implementar algo similar a una guía telefónica. Ninguna de las estructuras de datos que ha visto antes es adecuada para una guía telefónica.

Aquí es cuando un diccionario puede resultar útil. Los diccionarios se componen de pares clave-valor. La clave se utiliza para identificar el artículo y el valor se mantiene como sugiere el nombre, el valor del artículo.

In [90]:
x_dict = {'Company 01':1, 'Company 02':5, 'Company 03':4, 'Company 04':6}

del x_dict['Company 03']

x_dict

{'Company 01': 1, 'Company 02': 5, 'Company 04': 6}

In [91]:
x_dict['Company 02'] # Prints the value stored with the key Company 02.

5

In [94]:
print(len(x_dict))
print(x_dict.keys())
x_dict.values()

3
dict_keys(['Company 01', 'Company 02', 'Company 04'])


dict_values([1, 5, 6])

### Files

Los archivos son tradicionalmente parte de las estructuras de datos. Un lenguaje de programación sin la capacidad de almacenar y recuperar información previamente almacenada difícilmente sería útil. 
La sintaxis para leer y escribir archivos en Python es similar a la de otros lenguajes de programación, pero mucho más fácil de manejar. Estas son algunas de las funciones básicas que lo ayudarán a trabajar con archivos usando Python:

In [92]:
# File modes (2nd argument): 'r'(read), 'w'(write), 'a'(appending), 'r+'(both reading and writing)
f = open('file_name', 'w')

# Reads entire file
#f.read() 

# Reads one line at a time
#f.readline() 

# Writes the string to the file, returning the number of char written
f.write('Add this line.') 

f.close()

#### Edwin Fernandez - BLID
Python para Actuarios Vida